# Generated by Django 3.2.7 on 2021-11-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='minimum_bid',
            field=models.DecimalField(decimal_places=0, max_digits=255, max_length=255),
        ),
    ]
