# Generated by Django 3.2.7 on 2021-11-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_minimum_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('minimum_bid', models.IntegerField(default=0)),
                ('product', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='minimum_bid',
            field=models.IntegerField(),
        ),
    ]
