# Generated by Django 3.2.7 on 2021-10-11 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20210213_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 19, 39, 49, 372050)),
        ),
        migrations.AlterField(
            model_name='wishlist_item',
            name='updateon',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 19, 39, 49, 373835)),
        ),
    ]
